# Generated by Django 5.1.6 on 2025-03-15 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_delete_stockhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMoviment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('movement_type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Saída')], max_length=10, verbose_name='Tipo de Movimentação')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Histórico de Estoque',
                'verbose_name_plural': 'Históricos de Estoque',
            },
        ),
    ]
