# Generated by Django 5.1.6 on 2025-04-20 06:30

import clients.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=50, null=True)),
                ('complement', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(max_length=17, validators=[clients.models.validate_phone])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[clients.models.validate_cpf])),
                ('rg', models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[clients.models.validate_rg])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
    ]
