# Generated by Django 5.1.6 on 2025-03-26 00:02

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[clients.models.validate_cpf]),
        ),
    ]
