# Generated by Django 5.1.6 on 2025-03-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outflow',
            name='numbering',
            field=models.CharField(choices=[('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44')], default='34', max_length=2),
        ),
    ]
