# Generated by Django 5.1.6 on 2025-03-26 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0004_outflow_client_outflow_created_by'),
        ('products', '0006_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='outflow',
            name='selling_price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cost_price_product_outflows', to='products.product'),
            preserve_default=False,
        ),
    ]
