# Generated by Django 5.1.6 on 2025-03-26 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0005_outflow_selling_price'),
        ('products', '0006_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outflow',
            name='selling_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selling_price_product_outflows', to='products.product'),
        ),
    ]
