# Generated by Django 5.1.6 on 2025-03-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0006_alter_outflow_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outflow',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
