# Generated by Django 5.1.6 on 2025-03-26 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0008_remove_outflow_selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outflow',
            name='client',
        ),
    ]
