# Generated by Django 5.1.6 on 2025-03-26 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_cpf'),
        ('outflows', '0009_remove_outflow_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='outflow',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outflows', to='clients.client'),
        ),
        migrations.AddField(
            model_name='outflow',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
