# Generated by Django 5.1.6 on 2025-03-29 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0013_remove_outflow_selling_price'),
        ('products', '0010_remove_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='outflow',
            name='sale_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referência da Venda'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado Em'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='numbering',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numeração'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outflows', to='products.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado Em'),
        ),
    ]
