# Generated by Django 5.1.6 on 2025-04-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0014_outflow_sale_reference_alter_outflow_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outflow',
            name='numbering',
        ),
    ]
