# Generated by Django 5.1.6 on 2025-05-13 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_users_alter_userprofile_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='tax_id',
            new_name='chpj',
        ),
        migrations.RemoveField(
            model_name='company',
            name='users',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='companies.company'),
        ),
    ]
