# Generated by Django 5.1.6 on 2025-05-14 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_chpj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='chpj',
            new_name='cnpj',
        ),
    ]
