# Generated by Django 5.1.6 on 2025-05-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_rename_chpj_company_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ie',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
