# Generated by Django 5.1.6 on 2025-03-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflow',
            name='numbering',
            field=models.CharField(default='00', max_length=2),
        ),
    ]
