# Generated by Django 5.1.6 on 2025-04-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0004_alter_inflow_numbering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inflow',
            name='numbering',
        ),
    ]
