# Generated by Django 5.1.6 on 2025-04-05 01:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_cpf'),
        ('products', '0011_remove_product_numbering'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sale_date'], 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'Item da Venda', 'verbose_name_plural': 'Itens da Venda'},
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_as_cashier', to=settings.AUTH_USER_MODEL, verbose_name='Caixa'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Insira a porcentagem de desconto', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Desconto (%)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='order_status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('pending', 'Pendente'), ('waiting', 'Aguardando pagamento'), ('canceled', 'Cancelado'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('finalized', 'Finalizado'), ('delivered', 'Entregue'), ('sent', 'Enviado')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Dinheiro'), ('card', 'Cartão'), ('pix', 'Pix'), ('boleto', 'Boleto')], max_length=20, null=True, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Venda'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total da Venda'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço de Custo'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='Venda'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço Unitário'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome do Vendedor'),
        ),
    ]
