# Generated by Django 5.1.6 on 2025-04-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_budget_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='order_status',
            field=models.CharField(blank=True, choices=[('draft', 'Rascunho'), ('pending', 'Pendente'), ('waiting', 'Aguardando pagamento'), ('finalized', 'Finalizado'), ('delivered', 'Entregue'), ('sent', 'Enviado'), ('canceled', 'Cancelado')], default='finalized', max_length=20, null=True, verbose_name='Status do Pedido'),
        ),
    ]
