# Generated by Django 5.1.6 on 2025-04-05 02:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_cpf'),
        ('sales', '0004_alter_sale_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name': 'Orçamento', 'verbose_name_plural': 'Orçamentos'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Pedido de Venda', 'verbose_name_plural': 'Pedidos de Venda'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sale_date'], 'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quote_status',
        ),
        migrations.AlterField(
            model_name='sale',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_as_cashier', to=settings.AUTH_USER_MODEL, verbose_name='Cashier'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Enter the discount percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Discount (%)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='Data de expiração do orçamento (aplicável apenas para orçamentos)', null=True, verbose_name='Data de Validade'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='order_status',
            field=models.CharField(blank=True, choices=[('draft', 'Rascunho'), ('pending', 'Pendente'), ('waiting', 'Aguardando pagamento'), ('finalized', 'Finalizado'), ('canceled', 'Cancelado'), ('delivered', 'Entregue'), ('sent', 'Enviado'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='finalized', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Dinheiro'), ('card', 'Cartão'), ('pix', 'Pix'), ('boleto', 'Boleto')], max_length=20, null=True, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sale Date'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Seller'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Sale Total'),
        ),
    ]
