# Generated by Django 5.1.6 on 2025-04-05 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_budget_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='budget_status',
        ),
    ]
