# Generated by Django 5.1.6 on 2025-03-29 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_seller_alter_sale_cashier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='seller',
        ),
    ]
