# Generated by Django 5.1.6 on 2025-04-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_sale_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Dinhiero'), ('card', 'Cartão'), ('pix', 'Pix'), ('boleto', 'Boleto')], max_length=20, null=True, verbose_name='Payment Method'),
        ),
    ]
