# Generated by Django 5.1.6 on 2025-03-15 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_stockhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockHistory',
        ),
    ]
