# Generated by Django 5.1.6 on 2025-03-26 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
