# Generated by Django 5.1.6 on 2025-04-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='numbering',
        ),
    ]
